---
title: 'CA Oil Spill Incidents in 2008'
author: "Meghan Fletcher"
date: "2/18/2021"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(janitor)
library(sf)
library(tmap)
library(gstat)
library(stars)
```

#### **Overview:** The maps within this report reveal the number of oilspill incident across California in 2008. Oil spill data was utilized from CA DFW Oil Spill Incident Tracking created by the California State Geoportal: https://map.dfg.ca.gov/metadata/ds0394.html


```{r}
# Read in the oil spill and CA shapefiles
ca_oil <- read_sf(here("ds394"), layer = "ds394") %>% 
  clean_names()

# st_crs(ca_oil)

ca_counties <- read_sf(here("ca_counties"), layer = "CA_Counties_TIGER2016") %>% 
  clean_names() %>% 
  select(name)

# st_crs(ca_counties)
```

```{r, include = FALSE}
# Make sure the coordinates of the data sets match
ca_coutnies <- st_transform(ca_counties, st_crs(ca_oil))
st_crs(ca_counties)
```

```{r, fig.cap="**Figure 1:** Each point on this map of Californiarepresents a specific oil spill incident from 2008 (Data: CA DFW Oil Spill Incident Tracking, 2008)."}
# Make exploratoy map to show where the CA oil spills have been
ggplot() +
  geom_sf(data = ca_counties, fill = "wheat") +
  geom_sf(data = ca_oil, 
          color = "deepskyblue4",
          alpha = 0.3,
          size = 1.2) +
  theme_minimal() +
  labs(x = "Latitude",y = "Longitude", title = "Oil Spill Incidents in California")
```

```{r, fig.cap="**Figure 2:** Utilizing an interactive map is useful in being able to more accuraltey pinpoint and view where each incident occurred in 2008 (CA DFW Oil Spill Incident Tracking, 2008)."}
tmap_mode("view")

tm_shape(ca_oil) +
  tm_dots(aes(color = "blue"))
```

```{r, echo = FALSE}
# Make new subset
ca_oil_subset <- ca_oil %>% 
  select(localecoun, geometry) %>% 
  rename(name = localecoun)
```

```{r, include = FALSE}
# Make sure coordinates match again
# ca_oil_subset %>% st_crs()
# ca_counties %>% st_crs()

ca_counties <- st_transform(ca_counties, st_crs(ca_oil_subset))
st_crs(ca_counties)
```

```{r}
# Join together
ca_oil_inland <- ca_counties %>% 
  st_join(ca_oil_subset)

# Get counts of inland oil spill events
oil_counts <- ca_oil_inland %>% 
  count(name.x)
```

```{r, fig.cap="**Figure 3:** The chloropleth map of California reveals which counties had the most oil spill incidents in 2008. The darkest counties are those that had the greatest number of incidents (Data: CA DFW Oil Spill Incident Tracking, 2008)."}

# Make a chloropleth map in ggplot
# fill color depends on count of inland oil spill events by county
ggplot(data = oil_counts) +
  geom_sf(aes(fill = n), color = "black", size = 0.1) +
  scale_fill_gradientn(colors = c("lightgrey", "aquamarine", "cyan", "deepskyblue","navy")) +
  theme_minimal() +
  labs(x = "Latitude", y = "Longitude", title = "Chloropleth Map of Oil Spill Incidents in 2008", fill = "Oil Spill Incidents") 
```








